In [1]:
!pip install tensorflow

In [2]:
import tensorflow as tf

In [3]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout

In [4]:
import pandas as pd
import numpy as np

In [5]:
data = pd.read_csv("Credit .csv")

In [6]:
data 

,age,job,marital,education,balance,housing,duration,campaign,approval
0,30.0,unemployed,married,primary,1787,no,79.0,1,no
1,33.0,services,married,secondary,4789,yes,220.0,1,no
2,35.0,management,single,tertiary,1350,yes,185.0,1,no
3,30.0,management,married,tertiary,1476,yes,199.0,4,no
4,59.0,blue-collar,married,secondary,0,yes,226.0,1,no
...,...,...,...,...,...,...,...,...,...
4516,99.0,services,married,secondary,-333,yes,329.0,5,no
4517,57.0,self-employed,married,tertiary,-3313,yes,-153.0,1,no
4518,57.0,technician,married,secondary,295,no,151.0,11,no
4519,28.0,blue-collar,married,secondary,1137,no,129.0,4,no


In [7]:
data['job'].unique()  

array(['unemployed', 'services', 'management', 'blue-collar',
       'self-employed', 'technician', 'entrepreneur', 'admin.', 'student',
       'housemaid', 'retired', 'unknown', nan], dtype=object)

In [8]:
job = {'admin.':0,'blue-collar':1,'entrepreneur':2,'housemaid':3,'management':4,'retired':5,'self-employed':6,'services':7,'student':8,'technician':9,'unemployed':10,'unknown':11}
data['job'] = data['job'].map(job)
data['marital'] = data['marital'].map({'married':0,'single':1,'divorced':2})
data['education'] = data['education'].map({'primary':0,'secondary':1,'tertiary':2})
data['housing'] = data['housing'].map({'yes':0,'no':1})
data['approval'] = data['approval'].map({'yes':0,'no':1})

In [9]:
data.drop_duplicates(inplace=True)

In [10]:
data.dropna(inplace=True)

In [11]:
data.isnull().sum()

age          0
job          0
marital      0
education    0
balance      0
housing      0
duration     0
campaign     0
approval     0
dtype: int64

In [12]:
x =data.drop('approval',axis=1)
y = data['approval']

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [14]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((3452, 8), (863, 8), (3452,), (863,))

In [15]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout

In [16]:
input_dim=8

In [17]:
model =Sequential()
# input layer
model.add(Dense(units=128,activation='relu',input_dim=input_dim))
# Dropout layer 
model.add(Dropout(0.2))
# Hidden layer

model.add(Dense(units = 64,activation='relu'))
model.add(Dense(units = 32,activation='relu'))
model.add(Dense(units = 16,activation='relu'))
model.add(Dense(units = 8,activation='relu'))
# output layer


model.add(Dense(units=1,activation='sigmoid'))


model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy','mae','mse'])

c:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\core\dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [18]:
model.fit(x_train,y_train,epochs=10,batch_size=32)

Epoch 1/10
108/108 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7970 - loss: 3.6646 - mae: 0.2525 - mse: 0.1981
Epoch 2/10
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8846 - loss: 0.6303 - mae: 0.2893 - mse: 0.1454
Epoch 3/10
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8743 - loss: 0.5366 - mae: 0.3262 - mse: 0.1554
Epoch 4/10
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8886 - loss: 0.4283 - mae: 0.2603 - mse: 0.1217
Epoch 5/10
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8763 - loss: 0.4224 - mae: 0.2590 - mse: 0.1217
Epoch 6/10
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8799 - loss: 0.3877 - mae: 0.2456 - mse: 0.1144
Epoch 7/10
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8753 - loss: 0.3897 - mae: 0.2335 - mse: 0.1119
Epoch 8/10
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8865 - loss: 0.3863 - mae: 0.2376 - mse: 0.1087
Epoch 9/10
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8861 - loss: 0.3552 - 

In [19]:
pred = model.predict(x_test)

27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step


In [20]:
# pred =pd.DataFrame(pred)

In [21]:
import numpy

In [22]:
pred =numpy.ravel(pred)

In [23]:
pred

array([0.97941417, 0.6765648 , 0.6839274 , 0.981678  , 0.9923455 ,
       0.7631392 , 0.7338877 , 0.7852553 , 0.97507507, 0.9699135 ,
       0.9612883 , 0.6796255 , 0.9774271 , 0.76101744, 0.8134875 ,
       0.9036508 , 0.8106271 , 0.72859025, 0.9960283 , 0.969796  ,
       0.97597367, 0.9944472 , 0.8072228 , 0.7624079 , 0.7873008 ,
       0.68393797, 0.98728365, 0.9854542 , 0.75322956, 0.9615631 ,
       0.7946935 , 0.94444907, 0.83371556, 0.81450343, 0.7731726 ,
       0.7125467 , 0.7655806 , 0.9549938 , 0.74632967, 0.98137563,
       0.69056505, 0.91286963, 0.7394153 , 0.99182546, 0.9027425 ,
       0.7591687 , 0.9991558 , 0.9132013 , 0.8846587 , 0.9486747 ,
       0.74002814, 0.7956469 , 0.9878314 , 0.98543197, 0.84004366,
       0.6803553 , 0.991674  , 0.7651378 , 0.79902947, 0.91391957,
       0.71569204, 0.94148755, 0.71806645, 0.98682225, 0.69768417,
       1.        , 0.75431556, 0.7951751 , 0.8164755 , 0.7811088 ,
       0.959677  , 0.97670287, 0.79909   , 0.77237916, 0.99598

In [24]:
y_test

1727    0
4133    1
2419    0
2111    1
3485    1
       ..
2559    1
371     1
2939    1
2108    1
2608    1
Name: approval, Length: 863, dtype: int64

In [25]:
output =pd.DataFrame({'actual':y_test,'prediction':(pred>=0.5).astype(int)})

In [26]:
output['prediction'].unique()

array([1])

In [27]:
output['actual'].unique()

array([0, 1])

In [28]:
# balancing 