In [1]:
!pip install numpy

In [2]:
import numpy as np
print("successfully installed")

successfully installed


In [3]:
print("numpy version:-",np.__version__) 

numpy version:- 2.1.3


In [4]:
# Array and list  

# Array similar data store krta hai hain
# array >>>>>>>[1,2,3,4,5,6,7,8,9] 

# list >>>>>>[1,2,3,4,5,6,7,8,9, "ritik", 2.5, True, [1,2,3]]

list convert into array

In [5]:
# lst = [1,2,3,4,5]
# print("type of list:-",type(lst))
# arr =np.array(lst)
# print(arr)
# print("type of array:-",type(arr))

In [6]:
arrr =np.array([1,2,3,4,5])

In [7]:
print(arrr)
print("type of array:-",type(arrr))

[1 2 3 4 5]
type of array:- <class 'numpy.ndarray'>


In [8]:
lst = list(range(1, 20)) # list function is used to create list and range function is used to create range

In [9]:
type(lst)
arr =np.array(lst)
arr 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [10]:
arr =np.arange(1,20) #arange function is used to create array 
type(arr)

numpy.ndarray

In [11]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [12]:
arr =np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [13]:
arr =np.zeros((5,10))  # 5 rows and 10 columns and zero is used to create array
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [14]:
arr=np.ones((5,10)) # one is used to create array
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [15]:
np.linspace(1,10,5) # linspace function is used to create array

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

1D array convert into 2D

In [16]:
arr=np.arange(0,30) # arange function is used to create array

In [17]:
arr.reshape(5,6) # reshape function is used to create array   

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [18]:
arr.reshape(10,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [19]:
arr=np.random.randint(1,5,9) # random function is used to create array
arr

array([1, 4, 1, 1, 1, 1, 4, 1, 3], dtype=int32)

In [20]:
arr=np.random.randint(1,5,(5,2)) # random function is used to create array
arr

array([[1, 2],
       [2, 4],
       [1, 2],
       [3, 1],
       [4, 1]], dtype=int32)

In [21]:
arr=np.random.random(10) # seed function is used to create array
arr

array([0.36631753, 0.93190141, 0.80432005, 0.00862935, 0.56538138,
       0.2705232 , 0.4075658 , 0.06147742, 0.73436199, 0.0378838 ])

In [22]:
arr=np.random.random((5,10)) # seed function is used to create array
arr

array([[0.86728351, 0.56818442, 0.7881044 , 0.15853769, 0.34031789,
        0.05395622, 0.43237342, 0.07244394, 0.46624999, 0.4757298 ],
       [0.85466158, 0.46616071, 0.03047452, 0.74853718, 0.65161968,
        0.83725612, 0.7270918 , 0.95905187, 0.65625899, 0.11475983],
       [0.18485544, 0.24037766, 0.53281544, 0.86034435, 0.29519697,
        0.62525417, 0.28076557, 0.33701568, 0.26291602, 0.96807791],
       [0.84540257, 0.1152495 , 0.87835084, 0.42151127, 0.70328373,
        0.83101089, 0.62618467, 0.47164712, 0.28928234, 0.04753813],
       [0.24793676, 0.59224638, 0.23467519, 0.34552983, 0.53620218,
        0.1620849 , 0.48184299, 0.2256195 , 0.9267777 , 0.21403   ]])

In [23]:
arr =np.arange(60).reshape(12,5) # seed function is used to create array

In [24]:
print("array shape :-",arr.shape)
print("array size:-",arr.size)
print("array data type:-",arr.dtype)
print("array dimension:-",arr.ndim)

array shape :- (12, 5)
array size:- 60
array data type:- int64
array dimension:- 2


In [25]:
arr.flatten() ##  2d array to 1d array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [26]:
arr.ravel() # 2d array to 1d array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [27]:
arr.shape

(12, 5)

In [28]:
arr.T.shape

(5, 12)

In [29]:
# 1D 
arr =np.arange(30)
arr[0]

np.int64(0)

In [30]:
# 1D 
arr =np.arange(30)
arr[0:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
arr =np.arange(30)
arr[0]=100
arr

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29])

In [32]:
# 2 D 
arr =np.arange(60).reshape(12,5)
print(arr)
arr[1]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]]


array([5, 6, 7, 8, 9])

In [33]:
arr =np.arange(60).reshape(12,5)
print(arr)
arr[1,1]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]]


np.int64(6)

In [34]:
arr[1,3:5]

array([8, 9])

In [35]:
arr[0:5,1:2]   # row (o:5 means 0 to 4), column 

array([[ 1],
       [ 6],
       [11],
       [16],
       [21]])

In [36]:
arr[7:8,4][0]=100
arr

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38, 100],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59]])

In [37]:
arr[11,4]

np.int64(59)

In [38]:
arr[-1,-1]

np.int64(59)

In [39]:
arr[-1][-1]

np.int64(59)

In [40]:
arr[11][-1]

np.int64(59)

In [41]:
# 3d array

In [42]:
arr =np.array(np.arange(225).reshape(5,15,3))
arr.ndim, arr.shape, arr.size, arr.dtype

(3, (5, 15, 3), 225, dtype('int64'))

In [43]:
arr[0]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [44]:
arr[0][2:]

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [45]:
arr[:,0,:]

array([[  0,   1,   2],
       [ 45,  46,  47],
       [ 90,  91,  92],
       [135, 136, 137],
       [180, 181, 182]])

In [46]:
arr[:,0:1,0:1]

array([[[  0]],

       [[ 45]],

       [[ 90]],

       [[135]],

       [[180]]])

In [47]:
arr[2][3][1]=200
arr[2]

array([[ 90,  91,  92],
       [ 93,  94,  95],
       [ 96,  97,  98],
       [ 99, 200, 101],
       [102, 103, 104],
       [105, 106, 107],
       [108, 109, 110],
       [111, 112, 113],
       [114, 115, 116],
       [117, 118, 119],
       [120, 121, 122],
       [123, 124, 125],
       [126, 127, 128],
       [129, 130, 131],
       [132, 133, 134]])

In [48]:
arr =np.array([3,2,1,5,4])

In [49]:
arr.sort()
arr

array([1, 2, 3, 4, 5])

In [50]:
arr+2

array([3, 4, 5, 6, 7])

In [51]:
arr*2

array([ 2,  4,  6,  8, 10])

In [52]:
arr-1

array([0, 1, 2, 3, 4])

In [53]:
arr/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [54]:
arr =np.array([3,2,1,5,4])
arr1 =np.array([3,2,1,5,4])
arr+arr1

array([ 6,  4,  2, 10,  8])